CREATE USER mysaas WITH PASSWORD 'mysaas';
CREATE DATABASE mysaas OWNER mysaas;
GRANT ALL PRIVILEGES ON DATABASE mysaas TO mysaas;
\connect mysaas;
GRANT CREATE ON SCHEMA public TO mysaas;

CREATE TABLE projects
(
    project_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name TEXT,
    summary TEXT,
    details TEXT,
    tags TEXT[],
    start_date date,
    end_date date
);