import type { Metadata } from "next";
import '@/assets/styles/globals.css';

export const metadata: Metadata = {
  title: "Ryan Taylors Portfolio",
  description: "Portfolio of Ryan Taylor",
  keywords: "AI, Machine Learning, Data Science, Software Engineering, Portfolio, Ryan Taylor",
}; 

const MainLayout = ( { children }: Readonly<{children: React.ReactNode;}>) => {
  return (
    <html lang="en">
      <body>
        <div>{children}</div>
      </body>
    </html>
  );
};

export default MainLayout;

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
